# Generated by Django 4.0.4 on 2022-06-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_obj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='merchant_obj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantsetting',
            name='price_include_vat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchantsetting',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='merchantsetting',
            name='vat_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
